import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import saveDataToFile from "./components/TempDb"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'story Time',
  description: 'Generated by yours truly',
}

// saveDataToFile()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
