import './globals.css'
import type { Metadata } from 'next'
import saveDataToFile from "./components/TempDb"

export const metadata: Metadata = {
  title: 'story Time',
  description: 'Generated by yours truly',
}

// saveDataToFile()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
